### ISSUE TITLE
Python Progress

### ISSUE THREAD

**Issue by Kydoimos97** [Kydoimos97/CapstoneMSBA2020#30]
```
# -*- coding: utf-8 -*-
"""
Created on Fri Mar  5 11:41:46 2021

@author: willem
"""

# In[1]:
import pandas as pd
import numpy as np


# In[2]
df = pd.read_csv("C:/Users/wille/OneDrive/MSF&MSBA/5. Spring 2021/IS 6496 MSBA Capstone 3/CapstoneMainDF.csv", index_col=0)
productsdf = pd.read_csv("C:/Users/wille/OneDrive/MSF&MSBA/5. Spring 2021/IS 6496 MSBA Capstone 3/ProductsDF.csv", index_col=0)

df.columns = map(str.lower, df.columns)

# In[3]
print(df.head(10))
print(list(df.columns))
print(format(df.shape))

# In[4]
print(productsdf.head(10))
print(list(productsdf.columns))
print(format(productsdf.shape))

# In[5]

productdict = dict(zip(productsdf.Item_ID, productsdf.Item_Desc))
df["product_name"] = df.item_id
df.product_name = df.product_name.map(productdict)


print(df.product_name.head(10))

# In[6]

# Creation of Price
df["Price"] = df["sales"] / df["quantity_sold"]

#Days open
first_open = df["open_date"].min()
df["date"] = pd.to_datetime(df["date"])
df["open_date"] = pd.to_datetime(df["open_date"])
df["days_open"] = (df["date"]-df["open_date"])
```

Will Upload Clean code tonight.

**Comment by Kydoimos97** [comment]
[Uploading CapstoneDFCsv.zip…]()

**Comment by Kydoimos97** [comment]
[CapstoneCSVFiles](https://download938.mediafire.com/3mzckyoif2rg/yf8gp8j7cwqdi4t/CapstoneDFCsv.zip)

**Comment by Kydoimos97** [comment]
`subdf = df.iloc[0:100000]
imputedf.isna().sum()
imputedf['maxtemp'].isna().sum()

one_day = 86400 # In epoch times
imputedf = df
i = 10000
days = one_day * 1
c = 9

len(sub)

imputedf = df
days = one_day*lag
counter = 0
c = 9
    
for i in range(len(imputedf)-1):
    error_counter = 0
    na_counter = 0
    if subdf.iloc[i,c] == "NaN":
        d = pd.Timestamp(imputedf.iloc[i,2].timestamp() - days, unit='s')
        l = imputedf.iloc[i,0]
        sub = imputedf.loc[(imputedf['date']==d) & (imputedf['site_id']== l)]
        if len(sub) > 0:
            rep = sub.iloc[1,c]
            imputedf.iloc[i,c] = rep
            na_counter = na_counter + 1
        else: 
            print("Error at date=",imputedf.iloc[i,2]," & Site_id = ", l)
            error_counter = error_counter + 1
    else:
        print("index : ",i," | NaN's imputed : ",na_counter," | Errors occured: ", error_counter)
        pass

`

Output: 

index :  99999  | NaN's imputed :  0  | Errors occured:  0
Traceback (most recent call last):

  File "<ipython-input-96-2af652d689cf>", line 4, in <module>
    if subdf.iloc[i,c] == "NaN":

  File "C:\Users\wille\anaconda3\envs\SQL\lib\site-packages\pandas\core\indexing.py", line 889, in __getitem__
    return self._getitem_tuple(key)

  File "C:\Users\wille\anaconda3\envs\SQL\lib\site-packages\pandas\core\indexing.py", line 1450, in _getitem_tuple
    self._has_valid_tuple(tup)

  File "C:\Users\wille\anaconda3\envs\SQL\lib\site-packages\pandas\core\indexing.py", line 723, in _has_valid_tuple
    self._validate_key(k, i)

  File "C:\Users\wille\anaconda3\envs\SQL\lib\site-packages\pandas\core\indexing.py", line 1358, in _validate_key
    self._validate_integer(key, axis)

  File "C:\Users\wille\anaconda3\envs\SQL\lib\site-packages\pandas\core\indexing.py", line 1444, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")

IndexError: single positional indexer is out-of-bounds

**Comment by Kydoimos97** [comment]
1. Index out of bounds. 
2. Can't save the object to global variables. All slices are momentary duplicates.
3. Check if the solution even works.
